### ISSUE TITLE
Validate that the example value matches to the schema

### ISSUE THREAD

**Issue by Sweetchuck** [APIDevTools/swagger-cli#37]
Currently the example value can have a different data structure that is defined in the schema and the `swagger-cli` doesn't rise an error.
```yaml
example:
    foo:
        bar: a
        baz: b
type: object
properties:
    foo:
        type: integer
        format: int32
        default: 0
```

I think it would be very useful if the example value would be validated against the corresponding schema.
