### ISSUE TITLE
Can't not bundle in Travis CI

### ISSUE THREAD

**Issue by nkthanh98** [APIDevTools/swagger-cli#41]
I try to bundle doc in travis but it's not success, Seems, it was a js error
**Note, build folder existed**

This is error
```bash
$ swagger-cli bundle -o build/swagger.bundle.yaml -t yaml swagger.yaml
Cannot read property 'mkdir' of undefined
```

This is .travis.yml
```yaml
language: node_js

node_js:
  - 8

before_install:
  - npm install swagger-cli
  - export PATH=$(npm bin):$PATH

script:
  - swagger-cli validate swagger.yaml

after_success:
  - swagger-cli bundle -o build/swagger.bundle.yaml -t yaml swagger.yaml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master

```
