### ISSUE TITLE
Validate null value in enums

### ISSUE THREAD

**Issue by mwxxhdb** [APIDevTools/swagger-cli#42]
Incorrect YAML
```yaml
EnumObject:
  type: string
  enum:
    - NULL
    - ITEM1
    - ITEM2
```

Correct YAML
```yaml
EnumObject:
  type: string
  enum:
    - 'NULL'
    - ITEM1
    - ITEM2
```

Issue: There are warnings if using the incorrect YAML in SwaggerHub, but swagger-cli said the document is valid.

Warnings from SwaggerHub: enum value should conform to its schema's `type`

Expect result: Same warning as SwaggerHub.
