### ISSUE TITLE
How to bundle paths?

### ISSUE THREAD

**Issue by rethab** [APIDevTools/swagger-cli#46]
Hi, we have several api specs that we would like to bundle into one spec. We're trying to follow the example from the [spec](https://swagger.io/docs/specification/using-ref/).
In a file `all.yaml`:
```yaml
paths:
  /users:
    $ref: '../resources/users.yaml'
  /users/{userId}:
    $ref: '../resources/users-by-id.yaml'
```

When I then run `swagger-cli bundle all.yaml`, it inlines the other yaml files 1:1 (starting with the line `openapi: 3.0.0`). Other things we tried:
- use `$ref: '../resources/users.yaml#/paths` --> inlines paths, but nested under `/users`
- modify the `users.yaml` to only contain a list of paths --> similar output as previous

How can we correctly bundle all paths?
Note that bundling schemas/models works though. It's just paths that don't work
