### ISSUE TITLE
pre-commit: no files to check

### ISSUE THREAD

**Issue by MT-Cash** [APIDevTools/swagger-cli#65]
I've added this to my pre-commit config:

```
-   repo: https://github.com/APIDevTools/swagger-cli
    rev: v4.0.4
    hooks:
    - id: swagger-validation
      args: ["validate", "spec.yaml"]
```

When I run it manually, I get:

```
$ swagger-cli validate spec.yaml
Swagger schema validation failed. 
  Additional properties not allowed: putty at #/paths//foo/{id}/bar/{bar_id}
 
JSON_OBJECT_VALIDATION_FAILED
```

But with pre-commit I get:

```
$ pre-commit run --all          
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Check Xml............................................(no files to check)Skipped
Check JSON...........................................(no files to check)Skipped
Check for added large files..............................................Passed
Check for merge conflicts................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
swagger-validation...................................(no files to check)Skipped
```
