### ISSUE TITLE
Combining multiple files can create circular references

### ISSUE THREAD

**Issue by WillowP** [APIDevTools/swagger-cli#74]
Hello, thank you for this excellent tool! I hope this isn't a duplicate, I didn't see anything that jumped out at me.

# Problem
I have a bit of openapi spec like this:

```yaml
# File 1
type: object
required:
  - Prop1
  - Prop2
properties:
  Prop1:
    $ref: './modules/Prop1.yml'
  Prop2:
    $ref: './modules/Prop2.yml'

# File 2: './modules/Prop1.yml'
allOf:
  - $ref: './Base.yml'
  - type: object
    properties:
      title:
        type: string

# File 3: './modules/Prop2.yml'
allOf:
  - $ref: './Base.yml'
  - type: object
    properties:
      title:
        type: string

# File 4: './modules/Base.yml'
type: object
properties:
  some_shared_property:
    type: string
```

When I run `swagger-cli bundle`, without setting `--dereference`, I end up with a `$ref` that looks like this:

```
"$ref": "#/...path_to_first_file_object/properties/Prop1/allOf/0"
```

Since `Prop1` and `Prop2` both live inside of `#/...path_to_first_file_object/properties`, this is causing a circular reference. I get the error: `$refs must reference a valid location in the document` when I try to view the output on https://editor.swagger.io/

## Expected behaviour:
I'd expect the circular reference to be avoided.

If this isn't enough info, I'd be happy to provide more :)
