### ISSUE TITLE
Validation of composite keywords (anyOf, oneOf, allOf)

### ISSUE THREAD

**Issue by raoulkent** [APIDevTools/swagger-cli#82]
Firstly, thank you for taking the time to read this, as it is unclear to me where the issues lay.

In a project that I am working on, we have in our OASv3 API specification the following issue:
We wish to allow the input of some particular property to be a `string` with either the format `date` or `date-time`.

Currently, our specification looks as follows:
```yaml
properties:
  foo:
    type: string
    oneOf:
    - format: date
    - format: date-time
```

This validates correctly, however it does not work with [oas-tools](https://oas-tools.github.io), the tooling we use for our Node application. Looking at the source code it was clear that it needed modifying. Changing it to:
```yaml
properties:
  foo:
    oneOf:
    - type: string
      format: date
    - type: string
      format: date-time
```
This works well with the tooling.

However, it is unclear to me whether one or both are valid from an OASv3 standpoint. From what I can gatehr
